name: unicorn_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"
flutter:
  uses-material-design: true
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon_unicorn.png"
flutter_native_splash:
  color: "#ffffff"
  image: "assets/splash_unicorn.png"
  fullscreen: true

